[[GR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "877d017b78e31c7953a437f6a5c8094d241a73dc"
os = "windows"

    [[GR.download]]
    sha256 = "a7d32d6ec8d86eb4ebf30a15b73bbf9049bc83a28ad6db7bd28de7b69d56291d"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.i686-w64-mingw32-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42e2fa70e346597bea3f68648ad3f29b12c083bd"
os = "windows"

    [[GR.download]]
    sha256 = "6feb6dc057b5608423f45e38110ae931712eb8e4ebf8386d0e6ddac4abe68804"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.x86_64-w64-mingw32-cxx11.tar.gz"
[[GR]]
arch = "aarch64"
git-tree-sha1 = "b196a37f620374e5fc85ac04c072873802aaaa6e"
os = "macos"

    [[GR.download]]
    sha256 = "7383b64369cafa3477d5d5ba479b1a0d2c8ba80cb7447839b40b9ab017c53c2b"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.aarch64-apple-darwin.tar.gz"
[[GR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "702f1158bf6b489cfb74872519332bb75d27cddf"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "2c523d910d3645d4a23f59e0387840c9a592af6874bc41c2335cac0e0ff637ab"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.aarch64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f66fed0c8fc1c6e3cef95d006c383ed1526d355"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "db6aaa308792d5f13edccbd54e850b5643ddd21dc1d4be65e62be54036e32269"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "150eb3c6fddaaa41b47b57291e1055a22e08c717"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "47a7357e4fc4bd084822a14006afbf5fa13b117e995488f0f930cce88d9a4254"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.i686-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f189e0069236a4b9b199db49e0c24c7f6f4f68bb"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "436199db6d3b1605ed7302977cd28bad7e208c31aca7956a01be0c9e2dcad815"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "377e9e9636f6c69ae1bfc588ccc6f27273838515"
os = "macos"

    [[GR.download]]
    sha256 = "ad78654226a55bdd27811cf69a6b737db4581c76c32e458f22a3f1e51823fd32"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.x86_64-apple-darwin.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c648eaa66ac9198461da964966c9c72e2e9d8bd"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "b436a5e9a5d2e55c3a3ac2624fddd2b90a75cd39af90911a1d7f9ee89acf66cd"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.x86_64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "2ed6cc11d26f96028dc19a147a0d68b06c70d58a"
os = "freebsd"

    [[GR.download]]
    sha256 = "1a75b02c6221ba9770d1f41367a28e635f796fd9cb3aedb61413f2e052d091e6"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.19+0/GR.v0.73.19.x86_64-unknown-freebsd.tar.gz"
