[[GR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "986591a9edd60bc61e0ee1caf797e56a220da609"
os = "windows"

    [[GR.download]]
    sha256 = "5c05094c2b04c890040e7c7f15c04a328a6da6dc527b1ab29d4e57585ab8c90a"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.i686-w64-mingw32-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0deced2939464d3c46425aefed973c9b42fffd77"
os = "windows"

    [[GR.download]]
    sha256 = "e515a7bbd3ef4d6b076b50520cde904fd1d9dd548cdd99b462c44a07130bd666"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.x86_64-w64-mingw32-cxx11.tar.gz"
[[GR]]
arch = "aarch64"
git-tree-sha1 = "8ef0aa8e0b9102c2dd615b1277e19c940003fab7"
os = "macos"

    [[GR.download]]
    sha256 = "9680b631b96ef4f9560eb9940c96decbdf44ec531fc82af01d808e07e2d8710b"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.aarch64-apple-darwin.tar.gz"
[[GR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "469582d5d502f0e00c5175209981da477d7eaead"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "604302a93c85f388e7d63d44ff37156178a6f3a8b1e25cd64798b35dae9c0f46"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.aarch64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f75ec0a58ebed737bbecbf08d6eacadb527b31f"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "58ec687cb5d11f48772faa68b86d0489c44e8b36462ccdc33f377392e0b0bf1d"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "156a66fb7325882702d4535d203037999fad3b6a"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "7acf5387e45fafc83dede05027f089a18e5a23ef9056be4380a70510ffe58a91"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.i686-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f661b3079ba208a8e5219b3b23a3718905725ee9"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "4fa513861e8d7f63f737e8eff11f561cd05c6aa923d64948d8d5a58b3d1b274c"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "4cb8296f29d44dbd32770ea1651944c37ec4aba6"
os = "macos"

    [[GR.download]]
    sha256 = "8f47d30ee1efb458008f5eb9bab5d431363279e68ad8e82fce1773e79053cb76"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.x86_64-apple-darwin.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f12ad8374eb73d540781925428624d5786de2755"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "f088fce264ccc5fdc6275d9218e73f7445a587899c4fb57371722c958d526c17"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.x86_64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "526f10b3cf1922224ad91b9d3a2d99187136b734"
os = "freebsd"

    [[GR.download]]
    sha256 = "27ea0ed01ea46c657f178dd98e4136bc09a552b9a3f2b66a41fd1479c4143c5b"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.21+0/GR.v0.73.21.x86_64-unknown-freebsd.tar.gz"
