name = "GR_jll"
uuid = "d2c73de3-f751-5644-a686-071e5b155ba9"
version = "0.52.0+0"

[deps]
Qt_jll = "ede63266-ebff-546c-83e0-1c6fb6d0efc8"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Fontconfig_jll = "a3f928ae-7b40-5064-980b-68af3947d34b"
Pixman_jll = "30392449-352a-5448-841d-b1acce4e97dc"
FFMPEG_jll = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
Cairo_jll = "83423d85-b0ee-5818-9007-b63ccbeb887a"
Libtiff_jll = "89763e89-9b03-5906-acba-b20f662cd828"
GLFW_jll = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Qhull_jll = "784f63db-0788-585a-bace-daefebcd302b"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"

[compat]
julia = "1.0"
