name = "GR_jll"
uuid = "d2c73de3-f751-5644-a686-071e5b155ba9"
version = "0.73.3+0"

[deps]
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Fontconfig_jll = "a3f928ae-7b40-5064-980b-68af3947d34b"
Pixman_jll = "30392449-352a-5448-841d-b1acce4e97dc"
FFMPEG_jll = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
Cairo_jll = "83423d85-b0ee-5818-9007-b63ccbeb887a"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
Libtiff_jll = "89763e89-9b03-5906-acba-b20f662cd828"
GLFW_jll = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
Qt6Base_jll = "c0090381-4147-56d7-9ebc-da0b1113ec56"

[compat]
JLLWrappers = "1.2.0"
julia = "1.6"
Cairo_jll = "1.16.1"
Bzip2_jll = "1.0.8"
FreeType2_jll = "2.10.4"
Libdl = "1"
Libtiff_jll = "~4.5.1"
Artifacts = "1"
Qt6Base_jll = "~6.5.2"
